version: '3.8'

services:
  php:
    build: .
    container_name: php_dev
    volumes:
      - .:/var/www/html   
    working_dir: /var/www/html
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t src"
    ports:
      - "8000:8000"
